<a href="https://colab.research.google.com/github/dylanwalker/MGSC496/blob/main/MGSC496_L06_working.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is the in-class notebook for MGSC496 Lecture 6.

In [1]:
import numpy as np

<hr/>
<img src="https://drive.google.com/uc?id=1sk8CSP26YY7sfyzmHGFXncuNRujkvu9v" align="left">

<font size=3 color="darkred">Exercise: Tile a chessboard with the correct colors</font>

First look up an image of a chessboard to see how the 8x8 board is tiled with black and white. Now, **add only three lines of code** below to tile the chess board with 'W' and 'B'. You will need to use slicing to do this.

<font size=2 color="blue">hint: One of your lines should set all cells to be the same color.</font>

In [2]:
# Try it out
chessboard = np.chararray((8,8), unicode=True)
# Insert only three lines of code here to tile the chessboard correctly with 'W' and 'B'
print(chessboard)
#chessboard[:,:] = 'B' # This is easier
chessboard[0:8:2, 0:8:2] = 'W'
chessboard[0:8:2, 1:8:2] = 'B'
chessboard[1:8:2, 1:8:2] = 'W'
chessboard[1:8:2, 0:8:2] = 'B'
print(chessboard)

[['' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '']]
[['W' 'B' 'W' 'B' 'W' 'B' 'W' 'B']
 ['B' 'W' 'B' 'W' 'B' 'W' 'B' 'W']
 ['W' 'B' 'W' 'B' 'W' 'B' 'W' 'B']
 ['B' 'W' 'B' 'W' 'B' 'W' 'B' 'W']
 ['W' 'B' 'W' 'B' 'W' 'B' 'W' 'B']
 ['B' 'W' 'B' 'W' 'B' 'W' 'B' 'W']
 ['W' 'B' 'W' 'B' 'W' 'B' 'W' 'B']
 ['B' 'W' 'B' 'W' 'B' 'W' 'B' 'W']]


<hr/>
<img src="https://drive.google.com/uc?id=1sk8CSP26YY7sfyzmHGFXncuNRujkvu9v" align="left">

<font size=3 color="darkred">Exercise: Make a two move tic-tac-toe game</font>


Use numpy to make an array that will represent a tic-tac-toe board. Since tic-tac-toe uses X's and O's, let's make it a character array. We can do this with:
```python
board = np.chararray((3,3), unicode=True)
```
Use the `input()` function to have the first player enter their move as `row,col`. Then process this string so that you can use numpy indexing to put an 'X" in the position in the array that the user indicated. Then, do the same thing for the 'O' player, but first you must check that the position they gave is not already occupied (and keep asking for a move until you get a valid move). Print out the board before and after the move.**Don't try to implement the entire tic-tac-toe game now**, just get two valid moves and update the board. 


In [13]:
# Try it out
board = np.chararray((3,3),unicode=True)
print(board)
move = input("Enter your move: ")
row, col = move.split(',')
row = int(row)
col = int(col)
print(f"{row}, {col}")
board[row,col]='X'
print(board)

legitMove2 = False
occupied = (board=='')
while not(legitMove2):
  move2 = input("Enter you move: ")
  row, col = move2.split(',')
  row = int(row)
  col = int(col)
  legitMove2 = occupied[row,col]
  if not(legitMove2):
    print("You can't go there.")

board[row,col]='O'
print(board)


[['' '' '']
 ['' '' '']
 ['' '' '']]
Enter your move: 2,1
2, 1
[['' '' '']
 ['' '' '']
 ['' 'X' '']]
Enter you move: 2,1
You can't go there.
Enter you move: 2,2
[['' '' '']
 ['' '' '']
 ['' 'X' 'O']]


In [11]:
occupied = (board=='')
print(occupied)

[[ True  True  True]
 [ True  True False]
 [ True  True  True]]


In [14]:
moves = [(1, 2) , (1, 2)]
(moves[0][0]==moves[1][0]) and (moves[0][1]==moves[1][1])

True

<hr/>
<img src="https://drive.google.com/uc?id=1sk8CSP26YY7sfyzmHGFXncuNRujkvu9v" align="left">

<font size=3 color="darkred">Exercise: Tic-Tac-Toe 2.0</font>


Suppose you are given a tic-tac-toe `board` that is a character array, (just as we had before). But unlike before, some of the squares filled in with X's and O's. 

<br />

1. Make a boolean array `hasX` where the cells are `True` whenever an X is in the cell. 
2. Count how many X's are in each row and column by using the `.sum(axis=1)` and `.sum(axis=0)`methods. Store these as variables `row_counts` and `col_counts`. Remember: If you sum over the rows (axis=0), then your result will be an array of counts for each columns, and vice versa.
3. Write a function `isWin()` that takes the arguments `board` and `player` ( either an `'X'` or an `'O'`) and returns `True` if any of the elements in `row_counts` or `col_counts` is equal to `3`. You may find the function `np.any()` helpful.


Now you can use your function to determine if either player won by getting 3 in a row or column. Of course, we still haven't checked the diagonals. **Don't worry about checking the diagonals for now.** 

Try changing the configuration of the board and testing out your function. Make sure it works are expected.




In [28]:
# Try it out
# Here's an example board with some moves (I'm just putting X's and ignoring O's for now)
#  You will want to change the position of the X's in order to test out your function
board = np.chararray((3,3),unicode=True)
board[2,0] = 'X'
board[1,1] = 'X'
board[2,2] = 'X'
print(board)


[['' '' '']
 ['' 'X' '']
 ['X' '' 'X']]


In [29]:
# 1. Define hasX, where the cells are True whenever an X is in the cell. This should be a single line that makes use of numpy
hasX = (board=='X')
print(hasX)

[[False False False]
 [False  True False]
 [ True False  True]]


In [32]:
# 2. Define row_counts and col_counts variables, which count how many X's are in each row and column using the .sum() method w/ arguments axis=0 or axis=1
col_counts = hasX.sum(axis=0)
row_counts = hasX.sum(axis=1)
print(row_counts)
print(row_counts==3)
row_win = np.any(row_counts==3)
print(row_win)


[0 1 2]
[False False False]
False


In [52]:
# 3. Write a function isWin() that takes board and player (this is just a variable that equals 'X' or 'O') and returns True if any of the elements of row_counts or col_counts equals 3
#    hint: you may find np.any() helpful
def isWin(board, player='X'):
  hasX = (board==player)
  col_counts = hasX.sum(axis=0)
  row_counts = hasX.sum(axis=1)
  diag1 = board[[0,1,2],[0,1,2]]
  diag2 = board[[0,1,2],[2,1,0]]
  diag1_win = np.all(diag1==player)
  diag2_win = np.all(diag2==player)
  row_win = np.any(row_counts==3)
  col_win = np.any(col_counts==3)
  return (row_win or col_win or diag1_win or diag2_win)



  


In [55]:
board = np.chararray((3,3),unicode=True)
board[1,0] = 'X'
board[1,1] = 'X'
board[1,2] = 'X'
print(board)
win = isWin(board,player='X')
print(win)

[['' '' '']
 ['X' 'X' 'X']
 ['' '' '']]
True


In [51]:
diag1 = board[[0,1,2],[0,1,2]]
print(diag1)
diag1Var = (diag1=='X')
print(diag1Var)
np.all(diag1Var)
np.all(diag1=='X')
#diag1Var==np.array([True,True,True])

['X' 'X' 'X']
[ True  True  True]


True

In [42]:
board[[0,1,2],[2,1,0]]

chararray(['', 'X', ''], dtype='<U1')

In [38]:
x = np.random.randint(0,10,9).reshape(3,3)
print(x)
rowInd = np.array([0,1,0])
colInd = np.array([2,0,0])
x[rowInd,colInd]


[[7 2 8]
 [8 2 0]
 [7 0 8]]


array([8, 8, 7])

In [ ]:
# The Full Tic-Tac-Toe game
board = np.chararray((3,3),unicode=True)
print(board)
noWinner = True
turn = 0
while noWinner:
  player = ['X','O'][(turn%2)] # Trick to alternate between player X and player O
  validMove = False
  while not(validMove):
    move = input(f"Player {player} enter your move as row,col:")
    row = int(move.split(',')[0])
    col = int(move.split(',')[1])
    if board[row,col]=='':
      validMove = True
    else:
      print("Sorry that position is already occupied!")
  board[row,col] = player
  print(board)
  noWinner = not(isWin(board,player))
  if not(noWinner):
    print(f"Congrats player {player}, you won!")
  turn += 1


<hr/>
<img src="https://drive.google.com/uc?id=1sk8CSP26YY7sfyzmHGFXncuNRujkvu9v" align="left">

<font size=3 color="darkred">Exercise: Split array vertically into two equal sized parts</font>

Suppose you have been given a rectangular array whose size is randomly generated and with arbitrary shape, except that its number of rows is guaranteed to be even. Your task is to split this array into two equally sized arrays and then print them out.


In [57]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
part1, part2 = np.vsplit(grid,[2])

In [64]:
part1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [65]:
part2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# Try it out
nrow = np.random.randint(1,15)*2
ncol = np.random.randint(1,30)
rectArray = np.arange(nrow*ncol).reshape((nrow,ncol))


In [ ]:
half_row = rectArray.shape[0]//2
first_half = rectArray[:half_row, :]
second_half = rectArray[half_row:, :]
#print(rectArray)
# Enter your code here
first, second = np.vsplit(rectArray,[half_row])
print(first.shape)
print(second.shape)

<hr/>

# Exercise: Egon's PKE Meter Network

Egon from the Ghostbusters has wired up a network of automatic PKE meters all throughout a famous new york hotel to detect and chart ghost activity. His system records an array of numbers -- one number for each location -- and locations that are more important to the hotel (e.g., ballroom, front desk, lobby, conference room, etc.) appear first in this list. Higher numbers indicate higher ghost activity.


In [78]:
import numpy as np
import string

# make the locations array
locations = ['ballroom', 'front desk', 'lobby']
locations.extend([f'conference room {letter}' for letter in string.ascii_uppercase])
locations.extend([f'honeymoon suite {i}' for i in range(1,7)])
locations.extend([f'suite {i}' for i in range(1,11)])
locations.extend([f'room {i}' for i in range(100,111)])
locations.extend([f'room {i}' for i in range(200,211)])
locations.extend([f'room {i}' for i in range(300,311)])
locations.extend([f'room {i}' for i in range(400,411)])
locations.extend([f'room {i}' for i in range(500,511)])
locations = np.array(locations)

# make the pke_readings array
pke_readings = np.random.uniform(low=0, high=100, size=100)

print(locations)
print(pke_readings)

['ballroom' 'front desk' 'lobby' 'conference room A' 'conference room B'
 'conference room C' 'conference room D' 'conference room E'
 'conference room F' 'conference room G' 'conference room H'
 'conference room I' 'conference room J' 'conference room K'
 'conference room L' 'conference room M' 'conference room N'
 'conference room O' 'conference room P' 'conference room Q'
 'conference room R' 'conference room S' 'conference room T'
 'conference room U' 'conference room V' 'conference room W'
 'conference room X' 'conference room Y' 'conference room Z'
 'honeymoon suite 1' 'honeymoon suite 2' 'honeymoon suite 3'
 'honeymoon suite 4' 'honeymoon suite 5' 'honeymoon suite 6' 'suite 1'
 'suite 2' 'suite 3' 'suite 4' 'suite 5' 'suite 6' 'suite 7' 'suite 8'
 'suite 9' 'suite 10' 'room 100' 'room 101' 'room 102' 'room 103'
 'room 104' 'room 105' 'room 106' 'room 107' 'room 108' 'room 109'
 'room 110' 'room 200' 'room 201' 'room 202' 'room 203' 'room 204'
 'room 205' 'room 206' 'room 207' 'r

1. Egon believes that only locations with pke readings of 75 or greater are worthy of the ghostbusters attention. How many locations have a pke reading equal to or bigger than 75?

In [ ]:
# Enter code here
(pke_readings>=75).sum()



2. Egon wants to dispatch his buddies (Ray, Venkman and Winston) to the first 3 locations of 75 or greater. (Hint: you may find [the function `np.where()` helpful](https://numpy.org/doc/stable/reference/generated/numpy.where.html) ). Write code to display the names of these locations.

In [ ]:
# Enter code here
locations[np.where(pke_readings>=75)[0][0:3]]


3. Egon found a bug in his PKE network. The first 5 readings in his `pke_readings` array that are less than 65 always report 8.6 points higher than they actually are. Write some code to correct that.  



In [ ]:
# Enter code here
print(pke_readings)
print(np.where(pke_readings<65)[0][0:5])
pke_readings[np.where(pke_readings<65)[0][0:5]] = pke_readings[np.where(pke_readings<65)[0][0:5]] - 8.6
print(pke_readings)

# Exercise: DiceRoller 3.0


Make a new dice roller program that takes the two arrays as inputs:
- diceSides - a 1-D numpy array holding the number of sides of each die
- numDice - a 1-D numpy array holding the number of dice

So for example, to roll 3 6-sided dice, 1 10 sided die and 4 20-sided dice, we would pass:
```
diceSides = [6, 10, 20]
numDice = [3, 1, 4]
```

Your program should output a tuple of 3 arrays:
- The result of roll (ie., the number on the top of all dice after the roll)
- The count of every critical failure (when a die rolled the lowest number it could) *for each type of die*
- The counts of every critical hit (when a die rolled the highest number it could) *for each type of die*

So, for example, rolling the dice from the example above might yield:
```
rolls = [ 1,  3,  6,  6,  1, 13, 19,  6]
critFails = np.array([ 1, 0, 1])
critHits =  np.array([ 1, 0, 0])
```
The first three elemenst of ``rolls`` are the 3 6-sided dice, the next one is a 10-sided die, and the last four are 20-sided dice.

There was one critical fail amongst the 6-sided dice, zero for the ten-sided die, and one amongst the 20-sided dice.

There was one critical hit amongst the 6-sided dice, zero for the ten-sided die, and zero amongst the 20-sided dice.


You may find the following useful:
* You can use [np.repeat()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html) to get an array holding the number of sides of each die you want to roll.
* [np.random.randint()](https://docs.scipy.org/doc/numpy/reference/random/generated/numpy.random.mtrand.RandomState.randint.html) can take an array as an argument for high.
* [np.cumsum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cumsum.html) calculates the running sum over an array.
* Remember [np.split()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html) can split an array into parts at the locations (indexes) specified.
* [np.hstack()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html) will stack a list of arrays horizontally


In [ ]:
def diceRoller(diceSides,numDice):
  diceToRoll = np.repeat(diceSides,numDice) # to roll each of the diceSides[i] exactly numDice[i] times, use np.repeat()
  rolls = np.random.randint(low=1,high=diceToRoll+1) # a roll means picking a random int between 1 and the (numSides of the dice + 1) 
  critFail = (rolls==1) # a die is a crit fail if it rolled a 1 (always the lowest number)
  critHit = (rolls==diceToRoll) # a die is a crit hit if it rolled a value equal to the number of sides of the die.
  splitLocs = numDice.cumsum()[:len(numDice)-1] # Use the cumsum() method to get the locations where to split the rolls array so that each subarray contains only one type of die
  critFailCounts = np.hstack([ l.sum() for l in np.split(critFail,splitLocs)]) # splitting gives you a list of np.arrays, summing each will count the number of crits. 
  critHitCounts= n p.hstack([ l.sum() for l in np.split(critHit,splitLocs)])   #      and then stacking them horizontally, gives you an array again.
  return (rolls, critFailCounts,critHitCounts)


In [ ]:
# Test it out:
diceRoller(np.array([4,20,10]),np.array([3,2,2])) # roll 3 4-sided, 2 20-sided, and 2 10-sided dice


In [ ]:
# Test it out again:
diceRoller(np.array([6,12,8]),np.array([10,2,3])) # roll 10 6-sided, 2 12-sided, and 3 8-sided dice

# Exercise: RPG Character Battle

Remember your RPG Character Creater?  

Make a function that implements battling between different RPG Characters (that you created with your character creator). 

A character should consist of a name and a number of different attributes, such as Strength, Defense, Hit Points (life), etc. (but these are just suggestions -- you can use whatever you want).

Here are some guidelines:
- Your battle systems should compare one attribute vs another to determine the likelihood of a hit.
- Use dice rolling to add randomness to the system.
- A battle should consist of two characters taking turns trying to attack one another. If an attack succeeds it should reduce the Hit Points (or life or whatever attribute). This continues until one of the characters Hit Points reaches zero (in which case, they lose the battle)
- Take advantage of the power of numpy and your existing dice roller code from the previous exercises
 - You should be able to accomplish this just by using arrays and **without using any explicit for loops**

For example, a simple system could roll a 20 sided die:
- If the roll is 20 its a hit
- If the roll is 1 its a fail
- If the roll is anything else, `hit = ((Strength + roll) > Defense)` where Strength is the value of the attacking character's strength and Defense is the value of the defending character's defense.   

That's just one suggestion, but you can devise your own rules to determine how characters fight. For example you could have both the attacking and defending character roll a dice and do `hit = ((Strength + roll1) > (Defense + roll2))`. It's up to you.


In [ ]:
# Enter your code here
# Answer
import numpy as np

def battle(char1,char2,numTurns=30,debug=False):
  char1AttackRolls = np.random.randint(1,21,numTurns)
  char2AttackRolls = np.random.randint(1,21,numTurns)
  char1HP = np.full(numTurns,char1['HP'])
  char2HP = np.full(numTurns,char2['HP'])
  char1CritHit = (char1AttackRolls==20)
  char1CritFail = (char1AttackRolls==1)
  char2CritHit = (char1AttackRolls==20)
  char2CritFail = (char1AttackRolls==1)
  char1Hits = (char1CritHit*1 +(~char1CritHit)&(~char1CritFail)*((char1['strength'] + char1AttackRolls)>char2['defense'])*1)
  char2Hits = (char2CritHit*1 +(~char2CritHit)&(~char2CritFail)*((char2['strength'] + char2AttackRolls)>char1['defense'])*1)
  char2HP -= char1Hits.cumsum()
  char1HP -= char2Hits.cumsum()
  char1WinsOn = np.argmax(char2HP==0) + (numTurns+1)*(char2HP.min()>0) # find the index of the first occurence where char2 had zero hitpoints (set to numTurns+1 if this never happened)
  char2WinsOn = np.argmax(char1HP==0) + (numTurns+1)*(char1HP.min()>0) # find the index of the first occurence where char1 had zero hitpoints (set to numTurns+1 if this never happened)
  if debug:
    print('BATTLE REPORT')
    print('-------------------------------------------------------------------')
    print(f"{'char1AttackRolls':<16s} = {char1AttackRolls}")
    print(f"{'char2AttackRolls':<16s} = {char2AttackRolls}")
    print(f"{'char1Hits':<16s} = {char1Hits}")
    print(f"{'char2Hits':<16s} = {char2Hits}")
    print(f"{'char1HP':<16s} = {char1HP}")
    print(f"{'char2HP':<16s} = {char2HP}")
    print(f"{'char1WinsOn':<16s} = {char1WinsOn}")
    print(f"{'char2WinsOn':<16s} = {char2WinsOn}")
    print('-------------------------------------------------------------------')
  if (char1WinsOn<=numTurns or char2WinsOn<=numTurns): # Either char1 or char1 died before the last turn
    if char1WinsOn <= char2WinsOn: # char1 wins; if a tie, they win because char1 attacks first
      print(f"{char1['name']} won on the {char1WinsOn+1} round.")
      print(f"{char1['name']} has {char1HP[char1WinsOn]} hitpoints remaining.")
    else:
      print(f"{char2['name']} won on the {char2WinsOn+1} round.")
      print(f"{char2['name']} has {char2HP[char2WinsOn]} hitpoints remaining.")
  else: # Both characters were still alive
    print(f"{char1['name']} and {char2['name']} fought with valor and both were bloodied, but remained standing at the end of the battle.")
    print(f"{char1['name']} has {char1HP[-1]} hitpoints remaining.")
    print(f"{char2['name']} has {char2HP[-1]} hitpoints remaining.")
    

char1 = {'name':'Dylanus','strength':4,'defense':5,'HP':5}
char2 = {'name':'Grarg the Ogre','strength':5,'defense':10,'HP':20}
battle(char1,char2,10, debug=True)